services:

    post_converter:
        class:        AppBundle\Request\Converter\PostConverter
        arguments:    [ @doctrine.orm.entity_manager ]
        tags:
            - { name: request.param_converter, priority: 1, converter: post_converter }
